kind: pipeline
type: exec
name: default

steps:

  - name: build
    commands:
      - sudo docker build . -t billford-server-${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    when:
      branch:
        - main

  - name: deploy
    commands:
#      - sudo docker container stop blog
#      - sudo docker container rm blog
      - sudo docker run --name billford-server -d  -p 4100:8080 billford-server-${DRONE_BRANCH}:${DRONE_BUILD_NUMBER}
    when:
      branch:
        - main